# Generated by Django 2.2.5 on 2019-09-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tausite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
