# Generated by Django 2.2.5 on 2019-10-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tausite', '0002_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
